### ISSUE TITLE
Restructure test framework

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-fileupload#2]
Execute one of the recent improvements to iptools, to simplify framework, see interactive-pioneers/iptools-jquery-modal@560b0a71ae7b81572b411622095eff2a37d23b68

**Comment by mpeters1** [comment]
current grunt qa and test tasks fail

**Comment by ain** [comment]
@mpeters1 please create a separate ticket. This is to restructure Mocha setup, specifically.

**Comment by mpeters1** [comment]
@GeorgMeyer23 @ain created https://github.com/interactive-pioneers/iptools-jquery-fileupload/issues/4
